# Generated by Django 4.1.1 on 2022-10-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_alter_user_options_room_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
    ]
