# Generated by Django 4.1.1 on 2022-10-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_message_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
